name: Build-Windows
on:  
  workflow_dispatch: 
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: Build project
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:

      #Cleanup Disk Space
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false #takes too much time
          docker-images: true
          swap-storage: true

      #Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      #Cache Library
      - name: Cache library 
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      #Run Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      #Diff Repo
      - name: Check Changes
        run: git status --verbose --verbose

      #Make Build 
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      #Publish Output
      - name: Output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build