name: Sandbox
on : [workflow_dispatch]

jobs:
  Build:
    name: Sandbox
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:

      #List Space
      - name: List Space 
        run: df -h

      #Cleanup Disk Space
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      #List Space
      - name: List Space 
        run: df -h

      #Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      #Cache
      - name: Cache library 
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
              
      #List Space
      - name: List Space 
        run: df -h
       